# <div style="font-family: 'Playfair Display', serif; font-weight:bold; letter-spacing: 0px; color:#FAF0EF; font-size:150%; text-align:center; padding:10px; background:#BEBF50; border-radius: 10px; box-shadow: 10px 10px 5px #FAF0EF;">🌟Homework  <br></div>

<a id="2"></a>
# <div style="font-family: 'Playfair Display', serif; font-weight:bold; letter-spacing: 1px; color:#FAF0EF; font-size:150%; text-align:left; padding:10px; background:#BEBF50; border-radius: 10px;">1.Q1. Pandas version</div>

## What version of Pandas did you install?
 

You can get the version information using the __version__ field: 🗝️ 

In [1]:
import pandas as pd
pd.__version__


'2.2.2'



## Getting the data 
For this homework, we'll use the Car Fuel Efficiency dataset
 
 

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv"
df = pd.read_csv(url)

print(df.head())   


   engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3         

<a id="2"></a>
# <div style="font-family: 'Playfair Display', serif; font-weight:bold; letter-spacing: 1px; color:#FAF0EF; font-size:150%; text-align:left; padding:10px; background:#BEBF50; border-radius: 10px;">Q2. Records count </div>

How many records are in the dataset?

In [3]:
len(df)


9704

<a id="2"></a>
# <div style="font-family: 'Playfair Display', serif; font-weight:bold; letter-spacing: 1px; color:#FAF0EF; font-size:150%; text-align:left; padding:10px; background:#BEBF50; border-radius: 10px;">Q3. Fuel types </div>

How many fuel types are presented in the dataset?

In [4]:
df['fuel_type'].nunique()


2

<a id="2"></a>
# <div style="font-family: 'Playfair Display', serif; font-weight:bold; letter-spacing: 1px; color:#FAF0EF; font-size:150%; text-align:left; padding:10px; background:#BEBF50; border-radius: 10px;">Q4. Missing values </div>

How many columns in the dataset have missing values?

In [12]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower               0
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [5]:
df.isnull().sum()[df.isnull().sum() > 0]


num_cylinders    482
horsepower       708
acceleration     930
num_doors        502
dtype: int64

<a id="2"></a>
# <div style="font-family: 'Playfair Display', serif; font-weight:bold; letter-spacing: 1px; color:#FAF0EF; font-size:150%; text-align:left; padding:10px; background:#BEBF50; border-radius: 10px;">Q5. Max fuel efficiency</div>

What's the maximum fuel efficiency of cars from Asia?

In [11]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()


23.759122836520497

<a id="2"></a>
# <div style="font-family: 'Playfair Display', serif; font-weight:bold; letter-spacing: 1px; color:#FAF0EF; font-size:150%; text-align:left; padding:10px; background:#BEBF50; border-radius: 10px;">Q6. Median value of horsepower </div>

In [ ]:
 
median_before = df['horsepower'].median()

 
most_freq = df['horsepower'].mode()[0]

 
df['horsepower'] = df['horsepower'].fillna(most_freq)

 
median_after = df['horsepower'].median()


In [9]:
median_before

149.0

In [10]:
median_after

152.0

 📜 Yes, it increased

<a id="2"></a>
# <div style="font-family: 'Playfair Display', serif; font-weight:bold; letter-spacing: 1px; color:#FAF0EF; font-size:150%; text-align:left; padding:10px; background:#BEBF50; border-radius: 10px;">Q7. Sum of weights </div>

Select all the cars from Asia
 
Select only columns vehicle_weight and model_year

Select the first 7 values

In [13]:
import numpy as np

X = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7).to_numpy()

In [14]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

Get the underlying NumPy array. Let's call it X

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX

In [16]:

XTX = X.T.dot(X)
XTX 

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [17]:
XTX.shape

(2, 2)

Invert XTX

In [18]:

XTX_inv = np.linalg.inv(XTX)
XTX_inv 

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200]

In [19]:

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [20]:




w = XTX_inv.dot(X.T).dot(y)
w.sum()


0.5187709081074016

In [21]:
print("Q7. Sum of weights:", w.sum())

Q7. Sum of weights: 0.5187709081074016


<a id="6"></a>
# <div style="font-family: 'Playfair Display', serif; font-weight:bold; letter-spacing: 1px; color:#FAF0EF; font-size:150%; text-align:left; padding:10px; background:#BEBF50; border-radius: 10px;"> FIN</div>